language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t niniko123/ninikona-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true niniko123/ninikona-client npm run test

after_success:
  - docker build -t niniko123/ninikona-client ./client
  - docker build -t niniko123/ninikona-worker ./worker
  - docker build -t niniko123/ninikona-server ./server
  - docker build -t niniko123/ninikona-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push niniko123/ninikona-client
  - docker push niniko123/ninikona-worker
  - docker push niniko123/ninikona-server
  - docker push niniko123/ninikona-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-east-2-992382386439
  bucket_path: multi-docker
  on:
    branches: master
  access_key_id: $AWS_ACCESS_KEY
  access_secret_key: "$AWS_SECRET_KEY"
