language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t niniko123/ninikona-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true niniko123/ninikona-client npm run test

after_success:
  - docker build -t niniko123/ninikona-client ./client
  - docker build -t niniko123/ninikona-worker ./worker
  - docker build -t niniko123/ninikona-server ./server
  - docker build -t niniko123/ninikona-nginx ./nginx