version: '3'
services:
  client:
    image: 'niniko123/niniko-client'
    mem_limit: 128m
    hostname: client
  api:
    image: 'niniko123/ninikona-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_PORT=$PG_PORT
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
  worker:
    image: 'niniko123/ninikona-worker'
    mem_limit: 128m
    hostnname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'niniko123/ninikona-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
