version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PG_PORT=5432
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres_password
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "9096:80"